#ifndef PUMP_AC_CONFIG_H
#define PUMP_AC_CONFIG_H

// pump_core version info
#ifndef PUMP_AC_VERSION_MAJOR
#   define PUMP_AC_VERSION_MAJOR 0
#endif // !PUMP_AC_VERSION_MAJOR
#ifndef PUMP_AC_VERSION_MINOR
#   define PUMP_AC_VERSION_MINOR 0
#endif // !PUMP_AC_VERSION_MINOR
#ifndef PUMP_AC_VERSION_PATCH
#   define PUMP_AC_VERSION_PATCH 9
#endif // !PUMP_AC_VERSION_PATCH
#ifndef PUMP_AC_VERSION_BUILD
#   define PUMP_AC_VERSION_BUILD 0
#endif // !PUMP_AC_VERSION_BUILD
#define __PUMP_AC_VERSION_STR(str_) #str_
#define __PUMP_AC_VERJOIN(major_,minor_,patch_,build_) __PUMP_AC_VERSION_STR(major_.minor_.patch_.build_)
#define PUMP_AC_VERSION __PUMP_AC_VERJOIN(PUMP_AC_VERSION_MAJOR,PUMP_AC_VERSION_MINOR,PUMP_AC_VERSION_PATCH,PUMP_AC_VERSION_BUILD)

#endif //PUMP_AC_CONFIG_H