message("<pump> /cmake/compiler_conf.cmake in")

message("<pump> CMAKE_GENERATOR=" ${CMAKE_GENERATOR})
message("<pump> CMAKE_C_COMPILER=" ${CMAKE_C_COMPILER})
message("<pump> CMAKE_CXX_COMPILER=" ${CMAKE_CXX_COMPILER})
if(${CMAKE_GENERATOR} STREQUAL "Unix Makefiles")
    set(pump_COMPILER gcc)
    if(${pump_CPUARCH_FLAGE} STREQUAL "x64")
        add_compile_options(-m64)
    elseif(${pump_CPUARCH_FLAGE} STREQUAL "x32")
        add_compile_options(-m32)
    endif()
elseif(${CMAKE_GENERATOR} STREQUAL "MinGW Makefiles")
    set(pump_COMPILER gcc)
    if(${pump_CPUARCH_FLAGE} STREQUAL "x64")
        add_compile_options(-m64)
    elseif(${pump_CPUARCH_FLAGE} STREQUAL "x32")
        add_compile_options(-m32)
    endif()
elseif(${CMAKE_GENERATOR} STREQUAL "MSYS Makefiles")
elseif(${CMAKE_GENERATOR} STREQUAL "Borland Makefiles")
elseif(${CMAKE_GENERATOR} STREQUAL "NMake Makefiles JOM")
elseif(${CMAKE_GENERATOR} STREQUAL "NMake Makefiles")
elseif(${CMAKE_GENERATOR} MATCHES "Visual Studio")
    set_property(GLOBAL PROPERTY USE_FOLDERS On)
    add_definitions(-D_CRT_SECURE_NO_WARNINGS)
    if(${CMAKE_GENERATOR} STREQUAL "Visual Studio 14 2015")
        set(pump_COMPILER vc14)
        set(pump_CPUARCH_FLAGE x86)
    elseif(${CMAKE_GENERATOR} STREQUAL "Visual Studio 14 2015 Win64")
        set(pump_COMPILER vc14)
        set(pump_CPUARCH_FLAGE x64)
    elseif(${CMAKE_GENERATOR} STREQUAL "Visual Studio 12 2013")
        set(pump_COMPILER vc12)
        set(pump_CPUARCH_FLAGE x86)
    elseif(${CMAKE_GENERATOR} STREQUAL "Visual Studio 12 2013 Win64")
        set(pump_COMPILER vc12)
        set(pump_CPUARCH_FLAGE x64)
    elseif(${CMAKE_GENERATOR} STREQUAL "Visual Studio 10")
        set(pump_COMPILER vc10)
        set(pump_CPUARCH_FLAGE x86)
    elseif(${CMAKE_GENERATOR} STREQUAL "Visual Studio 10 Win64")
        set(pump_COMPILER vc10)
        set(pump_CPUARCH_FLAGE x64)
    elseif(${CMAKE_GENERATOR} STREQUAL "Visual Studio 9 2008")
        set(pump_COMPILER vc9)
        set(pump_CPUARCH_FLAGE x86)
    elseif(${CMAKE_GENERATOR} STREQUAL "Visual Studio 9 2008 Win64")
        set(pump_COMPILER vc9)
        set(pump_CPUARCH_FLAGE x64)
    elseif(${CMAKE_GENERATOR} STREQUAL "Visual Studio 8 2005")
        set(pump_COMPILER vc8)
        set(pump_CPUARCH_FLAGE x86)
    elseif(${CMAKE_GENERATOR} STREQUAL "Visual Studio 8 2005 Win64")
        set(pump_COMPILER vc8)
        set(pump_CPUARCH_FLAGE x64)
    elseif(${CMAKE_GENERATOR} STREQUAL "Visual Studio 6")
        set(pump_COMPILER vc6)
        set(pump_CPUARCH_FLAGE x86)
    endif()
elseif(${CMAKE_GENERATOR} STREQUAL "Watcom WMake")
elseif(${CMAKE_GENERATOR} STREQUAL "CodeBlocks - MinGW Makefiles")
elseif(${CMAKE_GENERATOR} STREQUAL "CodeBlocks - NMake Makefiles")
elseif(${CMAKE_GENERATOR} STREQUAL "CodeBlocks - Unix Makefiles")
elseif(${CMAKE_GENERATOR} STREQUAL "Eclipse CDT4 - MinGW Makefiles")
elseif(${CMAKE_GENERATOR} STREQUAL "Eclipse CDT4 - NMake Makefiles")
elseif(${CMAKE_GENERATOR} STREQUAL "Eclipse CDT4 - Unix Makefiles")
endif()

message("<pump> /cmake/compiler_conf.cmake out")